<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Vira" name="Sending mail" tests="2" failures="1" timestamp="5 Nov 2015 18:23:10 GMT" time="33.244" errors="0">
  <testcase name="failedMethod1" time="0.016" classname="com.gmail.verifications.Index">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.gmail.verifications.Index.failedMethod1(Index.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- failedMethod1 -->
  <testcase name="passedMethod" time="5.0" classname="com.gmail.verifications.Index"/>
</testsuite> <!-- Sending mail -->
